export enum SystemErrorCode {
  INVALID_INPUT = 'SYS_001',
  VALIDATION_FAILED = 'SYS_002',
  FORBIDDEN = 'SYS_003',
  UNAUTHORIZED = 'SYS_004',
  SERVICE_UNAVAILABLE = 'SYS_005',
  IDEMPOTENCY_KEY_REQUIRED = 'SYS_006',
  IDEMPOTENCY_KEY_INVALID = 'SYS_007',
  IDEMPOTENCY_KEY_CONFLICT = 'SYS_008',
  IDEMPOTENCY_KEY_NOT_FOUND = 'SYS_009',
  IDEMPOTENCY_KEY_PAYLOAD_MISMATCH = 'SYS_010',
  TOO_MANY_REQUESTS = 'SYS_011',
  UNCAUGHT_EXCEPTION = 'SYS_999',
}
