export enum SystemErrorCode {
  INVALID_INPUT = 'SYS_001',
  VALIDATION_FAILED = 'SYS_002',
  FORBIDDEN = 'SYS_003',
  UNAUTHORIZED = 'SYS_004',
  SERVICE_UNAVAILABLE = 'SYS_005',
  UNCAUGHT_EXCEPTION = 'SYS_999',
}
