export enum OrderErrorCode {
  NOT_FOUND = 'ORD_001',
  NOT_CANCELABLE = 'ORD_002',
  ORDER_NOT_FOUND = 'ORD_003',
  CREATE_ORDER_FAILED = 'ORD_004',
  DELETE_ORDER_FAILED = 'ORD_005',
  UPDATE_ORDER_FAILED = 'ORD_006',
  WORKFLOW_FAILED = 'ORD_999',
}
